list_at_casino = ["1429 Uncharted Seas", "300 Shields", "African Quest", "Alchymedes", "All Aces Poker",
                  "Art of the Heist", "AstroLegends: Lyra and Erion", "Baker's Treat", "Beautiful Bones",
                  "Bloodsuckers", "Big Bang", "Bikini Party", "Book of Oz", "Bookie of Odds",
                  "Break Da Bank Again Respin", "Castle Builder", "Castle Builder II", "Cazino Cosmos",
                  "Champion of the Track", "Cool Buck", "Craps", "Cupid Strike 2", "Dark Vortex", "Dead or Alive",
                  "Devil's Delight", "Divine Forest", "Double Dragons", "Dr.Jekyll and Mr.Hyde",
                  "Dragon Dance", "Dwarf Mine", "Dead or Alive 2", "Egyptian Dreams Deluxe", "Eye of the Kraken",
                  "Forsaken Kingdom", "Fruitbat Crazy", "Gems Odyssey 92", "Gems Odyssey", "Golden Legend",
                  "Golden Beauty", "Immortal Romance", "Happy Halloween", "Holmes and the Stolen Stones",
                  "Hot Ink", "Hugo 2", "Jackpot Jester 20", "Jackpot Raiders", "Jackpot 6000", "Jackpot Jester 50 k",
                  "Joker Pro", "Jade Butterfly", "Jokerizer", "Kings of Chicago", "Knockout Football", "Lil Devil",
                  "Le Kaffee Bar", "Lemur Does Vegas", "London Hunter", "Lucky Angler", "Magic Oak", "Magic of Sahara",
                  "MaxQuest: Wrath of Ra", "Medusa", "Mega Boy", "Mines of Gold", "MULTIFRUIT 81", "Mega Joker",
                  "Ninja", "Ozwin’s Jackpots", "Pearls of India", "Peek - a - Boo - 5 Reel", "Pets Go Wild",
                  "Pimped", "Pinocchio", "Pumpkin Patch", "Queen of Gold", "Rage to Riches", "Reel Gems", "Reel Rush 2",
                  "Reel Steal", "Retro Reels Diamond Glitz", "Retro Reels Extreme Heat", "Retro Reels",
                  "Robin Hood: Shifting Riches", "Rocket Dice", "Roo Riches", "Royal Masquerade", "Reel Heist",
                  "Santa’s Village", "Scarab Treasure", "Scrooge", "Scudamore's Super Stakes", "Sea Hunter",
                  "Serengeti Kings", "Skulls Up", "Stardust and Pinocchio", "Simsalabim",
                  "Single Deck Blackjack Professional Series", "Spectacular Wheel of Wealth", "Spina Colada",
                  "Spinfinity Man", "Split Way Royal", "Stardust", "Sugar Pop", "Sugar Pop 2: Double Dipped",
                  "Summer Splash", "Super 7 Blackjack", "Super Fast Hot Hot Respin",
                  "Street Fighter II: The World Warrior Slot", "Surfin' Reels", "Take The Bank", "Tens or Better",
                  "The Dark Knight", "The Dark Knight Rises", "The Dark Joker Rizes", "The French Roulette",
                  "The Wish Master", "Three Card Rummy", "Tomb Raider - Secret of the Sword", "Tomb Raider",
                  "Tomb Raider 2", "Three Musketeers", "Tower Quest", "Tree of Fortune", "Triple Edge Poker",
                  "Tut's Twister", "TXS Hold'em Professional Series", "Untamed Bengal Tiger", "Untamed Crowned Eagle",
                  "Untamed Giant Panda", "Untamed Wolf Pack", "Vampire: The Masquerade - Las Vegas",
                  "Vegas High Roller", "Vikings go Berzerk", "Vikings go to Hell", "Village People Macho Moves",
                  "Vip European Roulette", "Wheel of Wealth Special Edition", "Wheel of Wealth", "WhoSpunIt Plus",
                  "Wicked Circus", "Wild Orient", "Wild Swarm", "Wolf Hunters", "Zombie Hoard", "Zoom Roulette",
                  "The Royal Family", "Robin Hood: Shifting Riches"]
list_of_Rostik = ["Special OPS", "Mythical Beast", "10k Deluxe Scratchcard", "125k Deluxe Scratchcard",
                  "25k Deluxe Scratchcard", "7 11 21", "7-Up", "777", "Aces And Faces", "Aces and Eights",
                  "Astro Legends: Lyra and Erion", "Avalon Scratch", "Battle Mania", "Bird Jewelled",
                  "Bonus Deuces Wild", "Boss The Lotto", "Cashing Rainbows Pull Tab", "Christmas Deal", "Classic Wheel",
                  "Cricket Star Scratch", "Deuces Wild", "Diamond Deal Cashout", "Diamonds and Rubies",
                  "Dice Duel", "Disco Nights", "Dragon Tiger", "Epic Gems", "Fly Piggy Fly", "Fu 88", "Gamevy Tennis",
                  "Gems Odyssey", "Golden Hook", "Golden Koi", "Happy Holidays Scratch", "Incan Adventure",
                  "Jacks or Better", "Jingle Up", "Joker 8000", "Joker Poker", "Keno 80",
                  "Lost Vegas Survivors Scratch", "Lost Vegas Zombie Scratch", "Lucky 5", "Lucky 6", "Lucky 7",
                  "Lucky Leprechaun Scratch", "Mahjong Exchange", "Match Day", "Mega Money Rush", "Megamoney",
                  "Nerves of Steal", "Over the Rainbow", "Pets Go Wild", "Poke the Guy", "Pot Luck",
                  "Pull a Cracker Pull Tab", "Re-Trigger Happy Pull Tab", "Red Card", "Retro Solitaire", "Rio Bingo",
                  "Shuffle Bots Pull Tab", "Sic Bo", "Slot it in Pull Tab", "Space Force", "Speedy 7",
                  "Spin Dizzy Pull Tab", "Spinlotto", "Spinlotto Scratch", "Sunken Treasure",
                  "Super Expanding Splashcard", "Super Graphics Upside Down Pull Tab", "Super Showball",
                  "The Everlasting Scratchcard", "The Incredible Baloon Machine", "The Link", "The Link Scratch",
                  "Tutankhamun Pull Tab", "War Of Bets", "Wheel Of Fortune", "Cash Pool", "Crazy Donuts", "Cubes",
                  "Go Panda", "Mines", "Summer Scratch", "1001 Spins", "7 & Hot Fruits", "Might of Zeus",
                  "Wealth of Wisdom", "20 Golden Coins", "30 Spicy Fruits", "30 Summer Bliss", "Ice Valley",
                  "Jacks or Better", "Joker Poker", "Keno Universe", "Knight's Heart", "Orient Story",
                  "Buffalo Power Megaways", "Divine Dragon: Hold and Win", "Hit the Gold! Hold and Win",
                  "Rich Diamonds: Hold and Win", "Sun of Egypt 2", "Lobby", "Craps", "Draw high low",
                  "Pai Gow", "Pirate 21", "Pontoon 21", "Red Dog", "Three Card Rummy", "War", "Aces and Eights 1 Hand",
                  "Aces and Eights 5  Hand", "Aces and Eights 10 Hand", "Aces and Eights 100 Hand",
                  "Aces and Eights 50 Hand", "Before Time Runs Out", "Bonus Deuces Wild 1 Hand",
                  "Bonus Deuces Wild 5 Hand", "Bonus Deuces Wild 10 Hand", "Bonus Deuces Wild 50 Hand",
                  "Bonus Deuces Wild 100 Hand", "Caribbean Holdem", "Caribbean Stud", "Christmas Gift Rush",
                  "Deuces Wild 1 Hand", "Deuces Wild 5 Hand", "Deuces Wild 10 Hand", "Deuces Wild 50 Hand",
                  "Deuces Wild 100 Hand", "Double Exposure (3 Hand)", "Dragon Tiger", "Jacks or Better 1 Hand",
                  "Jacks or Better 5 Hand", "Jacks or Better 10 Hand", "Jacks or Better 50 Hand",
                  "Jacks or Better 100 Hand", "Orbs Of Atlantis", "Sic Bo", "Taberna De Los Muertos",
                  "Taberna De Los Muertos Ultra", "Tens or Better 1 Hand", "Tens or Better 5 Hand",
                  "Tens or Better 10 Hand", "Tens or Better 50 Hand", "Tens or Better 100 Hand", "War", "Bugs Party",
                  "Flying Pigs", "Keno", "Money Wheel", "Super Wheel", "Viking Runecraft Bingo", "Magnify Man",
                  "500 Juicy Fruits", "88 Bingo 88", "Bingo Soccer", "Fortune Craft", "Icy Fruits", "Just A Bingo",
                  "King of Jumping Scratch", "Lazy Monkey", "Master Of Gold", "Piggy Bank Scratch", "Shogun's Fortune",
                  "Draw Hi-Lo", "Pirate 21", "Pontoon", "Three Card Rummy", "Top Card Trumps",
                  "Age of Gods Norse: Norse Legends", "Age of the Gods Norse: Book of Dwarves",
                  "Age of the Gods: Book of Oracle", "Age of the Gods: Spin a Win", "Atlantis Cash Collect",
                  "Casino Hold 'Em", "Space Hunters: Shoot for Cash", "Fan Tan", "Punto Banco", "Aztec Gold Mines",
                  "Gold Digger: Mines", "Punto Banco", "Tens or Better", "Andar Bahar", "Dragon Tiger",
                  "Drops and Wins Lobby", "Mega Sic Bo", "Spaceman", "4 Dragon Kings", "Air Combat 1942", "Alter World",
                  "Animal Fishing", "Cai Shen Dao", "Fishing Expedition", "Force of Dragon", "Fruit Mountain",
                  "GO GO Magic Dog", "Giant Fish Hunter", "Go Go Magic Cat", "Golden Dragon", "Iron Chicken Hunter",
                  "KA Fish Hunter", "King Octopus", "Legend Of Erlang", "Mermaid Hunter", "Mermaid World",
                  "Monster Island", "Poseidon Secret", "Romance of the Three Kingdoms", "Shock Tower", "Space Cat",
                  "Space Cowboy", "Super Keno", "The Deep Monster", "Three Headed Dragon", "Undersea Battle",
                  "Zombie Chicken", "Balloon", "Cappadocia", "Cricket X", "JetX", "JetX3", "PlinkoX", "SpinX",
                  "Three Cards", "Darts 180", "FireFly Keno", "Keno Pop", "Tutan Keno", "Virtual Soccer",
                  "Sheriff's Justice", "Double Exposure", "Heads and Tails", "Heads and Tails XY", "Hi-Lo"]

Ans = ['red', 'blue', 'green', 'white']  #
Word = ['red', 'white']  #

# Обычная разность(Множество из Ans не входящее в Word):
# result = list(set(Ans) - set(Word))

# список игр , которые есть во втором списке(ROSTIK) но нету у нас в бонус термзах (CASINO)
result = list(set(list_of_Rostik) - set(list_at_casino))
for casino in result:
    print(casino)
print(result)
